name: Build and Review PR
run-name: Build and Review PR #${{ github.event.pull_request.number }}

on:
  pull_request_target:
  # forky is rude and is going to do bad things here
  
jobs:
  ci:
    uses: im-open/.github-fake/.github/workflows/reusable-javascript-build.yml@v1
    with:
      action-name: ${{ github.repository }}
      default-branch: main
      readme-location: './README.md'
      files-with-code: 'action.yml,package.json,package-lock.json' # TODO:  Update if there are additional files or scripts that contain source code for the action
      folders-with-code: 'src,dist'                                # TODO:  Update if there are additional directories that contain source code for the action
      build-command: 'npm run build'                               # TODO:  Update if a different command is used to build/recompile/format the action
    secrets:
      PIPELINE_BOT_PAT: ${{ secrets.PIPELINE_BOT_PAT }}   

  bad-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am a fork that changed the trigger of this build"
      - run: echo "This is the secret I'm going to take - ${{ secrets.FAKE_SECRET }}"
