name: Build and Review PR
run-name: Build and Review PR #${{ github.event.pull_request.number }}
on:
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
  #
  # This workflow uses the pull_request trigger which prevents write permissions on the
  # GH_TOKEN and secrets access from public forks.  This should remain as a pull_request
  # trigger to minimize the access public forks have in the repository.  The reduced 
  # permissions is adequate but does mean re-compiles and readme changes will have to be 
  # made manually by the PR author.  These auto-updates could be done by this workflow
  # for branches but in order to re-trigger a PR build (which is needed for status checks),
  # we would make the commits with a different user and their PAT.  To minimize exposure 
  # and complication we will request those changes be manually made by the PR author.
  pull_request:
    types: [opened, synchronize, reopened]
  # paths:
  #   Do not include specific paths here.  We always want this build to run and produce a
  #   status check which are branch protection rules can use.  If this is skipped because of
  #   path filtering, a status check will not be created and we won't be able to merge the PR
  #   without disabling that requirement.  If we have a status check that is always produced,
  #   we can also use that to require all branches be up to date before they are merged.

jobs:
  build-and-review-pr:
    uses: im-open/.github/.github/workflows/reusable-build-and-review-pr.yml@reusable-refactor
    with:
      action-name: ${{ github.repository }}
      default-branch: main
      readme-name: 'README.md'
      contribution-id: '#stuff'
      files-with-code: 'action.yml,package.json,package-lock.json'
      dirs-with-code: 'src,dist'                                
      build-command: 'npm run build'
