name: Post Build
run-name: Post-Build and Review for PR #${{ github.event.pull_request.number }}

on:
  workflow_run:
    workflows: [Build and Review PR]
    types: [completed]

jobs:
  post-build-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print previous workflow conclusion
        run: echo "The previous workflow conclusion is - '${{ github.event.workflow_run.conclusion}}'"
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      
      - name: Print a var
        run: echo "The fake variable is ${{ vars.FAKE_VARIABLE }}"
      
      - name: Print a secret
        run: echo "The fake secret is ${{ secrets.FAKE_SECRET }}"

      - run: echo "The github.ref is '${{ github.ref }}'"

  post-build-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print previous workflow conclusion
        run: echo "The previous workflow conclusion is - '${{ github.event.workflow_run.conclusion}}'"
      
